compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64

yarnPath: .yarn/releases/yarn-4.4.0.cjs
